import request from './request'
export const getStats = () => request.get('/admin/stats')
export const getAdminProducts = (p) => request.get('/admin/products', { params: p })
export const getAdminProduct = (id) => request.get(`/admin/products/${id}`)
export const createAdminProduct = (d) => request.post('/admin/products', d)
export const updateAdminProduct = (id, d) => request.put(`/admin/products/${id}`, d)
export const updateProductStatus = (id, s) => request.put(`/admin/products/${id}/status`, { status: s })
export const getAdminOrders = (p) => request.get('/admin/orders', { params: p })
export const getAdminOrder = (no) => request.get(`/admin/orders/${no}`)
export const getAdminSeckillProducts = (p) => request.get('/admin/seckill-products', { params: p })
export const createAdminSeckillProduct = (d) => request.post('/admin/seckill-products', d)
export const updateAdminSeckillProduct = (id, d) => request.put(`/admin/seckill-products/${id}`, d)
export const deleteAdminSeckillProduct = (id) => request.delete(`/admin/seckill-products/${id}`)
export const getAdminUsers = () => request.get('/admin/users')